import { createFileRoute } from "@tanstack/react-router";
import { Card, CardHeader, PageHeader } from "@/components/app-shell";
import { aiInsights, commandHistory } from "@/lib/mock";
import { Sparkles, Tag, TrendingUp, AlertTriangle, Smile } from "lucide-react";

export const Route = createFileRoute("/app/ai")({
  head: () => ({ meta: [{ title: "AI Insights — Command Center" }] }),
  component: AI,
});

function AI() {
  return (
    <div>
      <PageHeader title="AI Insights" description="Summarization, tagging, sentiment and risk scoring across every interaction." />

      <div className="grid gap-4 md:grid-cols-4">
        <Metric icon={Sparkles} label="Summarized" value={aiInsights.summarized.toLocaleString()} />
        <Metric icon={Tag} label="Tagged high-priority" value={String(aiInsights.taggedHigh)} />
        <Metric icon={TrendingUp} label="Avg confidence" value={`${(aiInsights.avgConfidence * 100).toFixed(0)}%`} />
        <Metric icon={Smile} label="Positive sentiment" value="71%" />
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-3">
        <Card>
          <CardHeader title="Priority distribution" />
          <div className="space-y-3 p-5">
            {[
              { l: "High", v: aiInsights.taggedHigh, tone: "bg-destructive" },
              { l: "Medium", v: aiInsights.taggedMed, tone: "bg-warning" },
              { l: "Low", v: aiInsights.taggedLow, tone: "bg-success" },
            ].map((b) => {
              const total = aiInsights.taggedHigh + aiInsights.taggedMed + aiInsights.taggedLow;
              const pct = (b.v / total) * 100;
              return (
                <div key={b.l}>
                  <div className="flex justify-between text-xs"><span>{b.l}</span><span className="text-muted-foreground">{b.v} ({pct.toFixed(1)}%)</span></div>
                  <div className="mt-1 h-2 rounded-full bg-muted">
                    <div className={`${b.tone} h-2 rounded-full`} style={{ width: `${pct}%` }} />
                  </div>
                </div>
              );
            })}
          </div>
        </Card>

        <Card>
          <CardHeader title="Top tags" description="AI-generated" />
          <div className="space-y-2 p-5">
            {aiInsights.topTags.map((t) => (
              <div key={t.tag} className="flex items-center justify-between rounded-md border border-border bg-background/40 px-3 py-2 text-xs">
                <span className="font-mono text-accent">#{t.tag}</span>
                <span className="text-muted-foreground">{t.count}</span>
              </div>
            ))}
          </div>
        </Card>

        <Card>
          <CardHeader title="Risk feed" description="High-risk interactions" />
          <div className="divide-y divide-border">
            {commandHistory.slice(0, 5).map((c) => (
              <div key={c.id} className="px-5 py-3">
                <div className="flex items-center justify-between text-xs">
                  <span className="font-mono text-accent">{c.name}</span>
                  <span className="inline-flex items-center gap-1 text-warning"><AlertTriangle className="h-3 w-3" /> medium</span>
                </div>
                <p className="mt-1 text-xs text-muted-foreground">{c.aiSummary}</p>
              </div>
            ))}
          </div>
        </Card>
      </div>

      <Card className="mt-6">
        <CardHeader title="Suggested actions" description="Auto-generated by the AI pipeline" />
        <div className="grid gap-3 p-5 md:grid-cols-2">
          {[
            { t: "Enable rate limit on /report", d: "Surge of 3x normal traffic from Atlas HQ in the last hour.", b: "Apply" },
            { t: "Promote /history to enabled", d: "Frequently invoked by moderators on Synthwave.", b: "Enable" },
            { t: "Tune webhook retry policy", d: "10% of failures recovered after 2 retries — bump to 3.", b: "Update" },
            { t: "Notify on new admin logins", d: "Activity history suggests irregular access pattern.", b: "Notify" },
          ].map((s) => (
            <div key={s.t} className="flex items-start justify-between gap-3 rounded-lg border border-border bg-background/40 p-4">
              <div>
                <div className="text-sm font-medium">{s.t}</div>
                <p className="mt-1 text-xs text-muted-foreground">{s.d}</p>
              </div>
              <button className="shrink-0 rounded-md bg-primary px-3 py-1.5 text-xs font-medium text-primary-foreground hover:opacity-90">{s.b}</button>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}

function Metric({ icon: Icon, label, value }: { icon: React.ComponentType<{ className?: string }>; label: string; value: string }) {
  return (
    <div className="rounded-xl border border-border bg-card p-5">
      <div className="grid h-8 w-8 place-items-center rounded-lg bg-primary/10 text-primary"><Icon className="h-4 w-4" /></div>
      <div className="mt-3 text-xs text-muted-foreground">{label}</div>
      <div className="mt-1 text-2xl font-semibold">{value}</div>
    </div>
  );
}
